# This file is generated by scripts/generate_volume.py. Do not edit by hand.
defmodule ExChurchOfJesusChrist.Scriptures.NewTestament.Data.FrontMatter do
  @moduledoc false

  def all do
    %{
      title_page: [
        "The New Testament",
        "of Our Lord and Saviour Jesus Christ",
        "Translated out of the Original Greek: and with the Former Translations Diligently Compared and Revised, by His Majesty's Special Command"
      ]
    }
  end
end
