# This file is generated by scripts/generate_volume.py. Do not edit by hand.
defmodule ExChurchOfJesusChrist.Scriptures.NewTestament.Data.FrontMatter do
  @moduledoc false

  def all do
    %{

    }
  end
end
