# This file is generated by scripts/generate_volume.py. Do not edit by hand.
defmodule ExChurchOfJesusChrist.Scriptures.PearlOfGreatPrice.Data do
  @moduledoc false

  def books do
    [
    ExChurchOfJesusChrist.Scriptures.PearlOfGreatPrice.Data.Moses,
    ExChurchOfJesusChrist.Scriptures.PearlOfGreatPrice.Data.Abraham,
    ExChurchOfJesusChrist.Scriptures.PearlOfGreatPrice.Data.JosephSmithMatthew,
    ExChurchOfJesusChrist.Scriptures.PearlOfGreatPrice.Data.JosephSmithHistory,
    ExChurchOfJesusChrist.Scriptures.PearlOfGreatPrice.Data.ArticlesOfFaith
    ]
  end
end
