# This file is generated by scripts/generate_volume.py. Do not edit by hand.
defmodule ExChurchOfJesusChrist.Scriptures.DoctrineAndCovenants.Data do
  @moduledoc false

  def books do
    [
    ExChurchOfJesusChrist.Scriptures.DoctrineAndCovenants.Data.DoctrineAndCovenants
    ]
  end
end
