# This file is generated by scripts/generate_volume.py. Do not edit by hand.
defmodule ExChurchOfJesusChrist.Scriptures.NewTestament.Data do
  @moduledoc false

  def books do
    [
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.Matthew,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.Mark,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.Luke,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.John,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.Acts,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.Romans,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.FirstCorinthians,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.SecondCorinthians,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.Galatians,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.Ephesians,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.Philippians,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.Colossians,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.FirstThessalonians,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.SecondThessalonians,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.FirstTimothy,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.SecondTimothy,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.Titus,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.Philemon,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.Hebrews,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.James,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.FirstPeter,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.SecondPeter,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.FirstJohn,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.SecondJohn,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.ThirdJohn,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.Jude,
    ExChurchOfJesusChrist.Scriptures.NewTestament.Data.Revelation
    ]
  end
end
