defmodule ExChurchOfJesusChrist.Scriptures.Volume do
  @moduledoc """
  Shared implementation for a volume of scripture, such as the Book of Mormon.

  A volume module calls `use ExChurchOfJesusChrist.Scriptures.Volume` with its
  generated data namespace, and gets the full reading API: `books/0`, `book/1`,
  `chapters/1`, `chapter/2`, `verse/3`, `lookup/1`, `search/2`, `stream/0` and
  friends. The data namespace is generated by `scripts/generate_volume.py`.

      defmodule ExChurchOfJesusChrist.Scriptures.BookOfMormon do
        use ExChurchOfJesusChrist.Scriptures.Volume,
          id: :book_of_mormon,
          name: "Book of Mormon",
          url_path: "bofm",
          data: ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data
      end

  Options:

    * `:id` - the volume's id atom
    * `:name` - the volume's display name
    * `:url_path` - the volume's path segment on churchofjesuschrist.org
      (`"ot"`, `"nt"`, `"bofm"`, `"dc-testament"`, `"pgp"`)
    * `:data` - the generated data namespace module
  """

  alias ExChurchOfJesusChrist.Scriptures.{Book, Chapter, Verse}

  @site "https://www.churchofjesuschrist.org/study/scriptures"

  @enforce_keys [:id, :name, :url_path, :data, :books, :book_ids, :name_index]
  defstruct [
    :id,
    :name,
    :url_path,
    :data,
    :books,
    :book_ids,
    :name_index,
    :chapter_count,
    :verse_count
  ]

  @type t :: %__MODULE__{}
  @type book_ref :: atom() | String.t() | Book.t()
  @type error :: :book_not_found | :chapter_not_found | :verse_not_found | :invalid_reference

  defmacro __using__(opts) do
    quote bind_quoted: [opts: opts] do
      alias ExChurchOfJesusChrist.Scriptures.{Book, Chapter, Verse, Volume}

      @volume Volume.build(opts)

      @doc "Returns this volume's compiled metadata (books, counts, name index)."
      @spec __volume__() :: Volume.t()
      def __volume__, do: @volume

      @doc "The volume's id atom."
      @spec id() :: atom()
      def id, do: @volume.id

      @doc "The volume's display name."
      @spec name() :: String.t()
      def name, do: @volume.name

      @doc "The volume's table of contents on churchofjesuschrist.org."
      @spec url() :: String.t()
      def url, do: Volume.volume_url(@volume)

      @doc "Returns every book in the volume, in canonical order."
      @spec books() :: [Book.t()]
      def books, do: Volume.books(@volume)

      @doc "Returns the id atoms of every book, in canonical order."
      @spec book_ids() :: [atom()]
      def book_ids, do: @volume.book_ids

      @doc """
      Finds a book by id atom, name, abbreviation or alias (case-insensitive).
      """
      @spec book(Volume.book_ref()) :: {:ok, Book.t()} | {:error, :book_not_found}
      def book(ref), do: Volume.book(@volume, ref)

      @doc "Like `book/1` but raises `ArgumentError` if the book does not exist."
      @spec book!(Volume.book_ref()) :: Book.t()
      def book!(ref), do: Volume.bang(book(ref), ref)

      @doc "Returns every chapter of a book, with verses."
      @spec chapters(Volume.book_ref()) :: {:ok, [Chapter.t()]} | {:error, :book_not_found}
      def chapters(ref), do: Volume.chapters(@volume, ref)

      @doc "Returns a single chapter of a book, with verses."
      @spec chapter(Volume.book_ref(), pos_integer()) ::
              {:ok, Chapter.t()} | {:error, :book_not_found | :chapter_not_found}
      def chapter(ref, number), do: Volume.chapter(@volume, ref, number)

      @doc "Like `chapter/2` but raises `ArgumentError` on failure."
      @spec chapter!(Volume.book_ref(), pos_integer()) :: Chapter.t()
      def chapter!(ref, number), do: Volume.bang(chapter(ref, number), {ref, number})

      @doc "Returns a single verse."
      @spec verse(Volume.book_ref(), pos_integer(), pos_integer()) ::
              {:ok, Verse.t()} | {:error, Volume.error()}
      def verse(ref, chapter, number), do: Volume.verse(@volume, ref, chapter, number)

      @doc "Like `verse/3` but raises `ArgumentError` on failure."
      @spec verse!(Volume.book_ref(), pos_integer(), pos_integer()) :: Verse.t()
      def verse!(ref, chapter, number),
        do: Volume.bang(verse(ref, chapter, number), {ref, chapter, number})

      @doc "Returns every verse of the volume as a lazy stream, in order."
      @spec stream() :: Enumerable.t(Verse.t())
      def stream, do: Volume.stream(@volume)

      @doc "Returns a uniformly random verse."
      @spec random_verse() :: Verse.t()
      def random_verse, do: Volume.random_verse(@volume)

      @doc """
      Parses a scripture reference without looking up any text.

      Supported forms are `"Book C"`, `"Book C:V"`, `"Book C:V-W"` and
      comma-separated verse lists such as `"Book C:V,W-X"`.
      """
      @spec parse_reference(String.t()) ::
              {:ok, %{book: atom(), chapter: pos_integer(), verses: :all | [pos_integer()]}}
              | {:error, :book_not_found | :invalid_reference}
      def parse_reference(reference), do: Volume.parse_reference(@volume, reference)

      @doc """
      Looks up the verses named by a scripture reference. A chapter-only
      reference returns every verse in the chapter.
      """
      @spec lookup(String.t()) :: {:ok, [Verse.t()]} | {:error, Volume.error()}
      def lookup(reference), do: Volume.lookup(@volume, reference)

      @doc "Like `lookup/1` but raises `ArgumentError` on failure."
      @spec lookup!(String.t()) :: [Verse.t()]
      def lookup!(reference), do: Volume.bang(lookup(reference), reference)

      @doc """
      Searches the text of every verse.

      A string query matches case-insensitively as a substring; a `Regex` is
      matched as given.

      ## Options

        * `:book` - restrict the search to one book
        * `:limit` - return at most this many verses
      """
      @spec search(String.t() | Regex.t(), keyword()) :: [Verse.t()]
      def search(query, opts \\ []), do: Volume.search(@volume, query, opts)

      @doc """
      Front matter of the volume (title pages, testimonies, and so on), keyed by
      atom, one string per paragraph.
      """
      @spec front_matter() :: %{atom() => [String.t()]}
      def front_matter, do: Module.concat(@volume.data, FrontMatter).all()

      @doc "Total number of chapters in the volume."
      @spec chapter_count() :: non_neg_integer()
      def chapter_count, do: @volume.chapter_count

      @doc "Total number of verses in the volume."
      @spec verse_count() :: non_neg_integer()
      def verse_count, do: @volume.verse_count
    end
  end

  ## Compile time

  @doc false
  def build(opts) do
    id = Keyword.fetch!(opts, :id)
    url_path = Keyword.fetch!(opts, :url_path)
    data = Keyword.fetch!(opts, :data)

    books =
      Enum.map(data.books(), fn module ->
        meta = module.metadata()
        chapters = module.chapters()

        {meta.id,
         %{
           module: module,
           url_slug: meta.url_slug,
           aliases: meta.aliases,
           book: %Book{
             id: meta.id,
             volume: id,
             order: meta.order,
             name: meta.name,
             abbreviation: meta.abbreviation,
             title: meta.title,
             subtitle: meta.subtitle,
             introduction: meta.introduction,
             chapter_count: length(chapters),
             verse_count:
               chapters |> Enum.map(fn {_, verses} -> length(verses) end) |> Enum.sum(),
             url: "#{@site}/#{url_path}/#{meta.url_slug}?lang=eng"
           }
         }}
      end)

    name_index =
      for {book_id, %{aliases: aliases, book: book}} <- books,
          name <- [book.name, book.abbreviation, Atom.to_string(book_id) | aliases],
          into: %{},
          do: {normalize(name), book_id}

    %__MODULE__{
      id: id,
      name: Keyword.fetch!(opts, :name),
      url_path: url_path,
      data: data,
      books: Map.new(books),
      book_ids: Enum.map(books, &elem(&1, 0)),
      name_index: name_index,
      chapter_count: books |> Enum.map(fn {_, e} -> e.book.chapter_count end) |> Enum.sum(),
      verse_count: books |> Enum.map(fn {_, e} -> e.book.verse_count end) |> Enum.sum()
    }
  end

  @doc false
  @spec normalize(String.t()) :: String.t()
  def normalize(name) do
    name
    |> String.downcase()
    |> String.replace(".", "")
    |> String.replace(~r/[\-–—_]/u, " ")
    |> String.replace(~r/\s+/u, " ")
    |> String.trim()
  end

  ## Runtime

  @doc false
  def volume_url(volume), do: "#{@site}/#{volume.url_path}?lang=eng"

  @doc false
  def books(volume), do: Enum.map(volume.book_ids, &volume.books[&1].book)

  @doc false
  def book(volume, ref) do
    with {:ok, id} <- resolve(volume, ref), do: {:ok, volume.books[id].book}
  end

  @doc false
  def chapters(volume, ref) do
    with {:ok, id} <- resolve(volume, ref) do
      entry = volume.books[id]
      {:ok, Enum.map(entry.module.chapters(), &build_chapter(volume, entry, &1))}
    end
  end

  @doc false
  def chapter(volume, ref, number) when is_integer(number) do
    with {:ok, id} <- resolve(volume, ref),
         entry = volume.books[id],
         {:ok, raw} <- fetch_chapter(entry, number) do
      {:ok, build_chapter(volume, entry, raw)}
    end
  end

  @doc false
  def verse(volume, ref, chapter, number) when is_integer(chapter) and is_integer(number) do
    with {:ok, id} <- resolve(volume, ref),
         entry = volume.books[id],
         {:ok, {^chapter, texts}} <- fetch_chapter(entry, chapter),
         {:ok, text} <- fetch_verse(texts, number) do
      {:ok, build_verse(volume, entry, chapter, number, text)}
    end
  end

  @doc false
  def stream(volume) do
    Stream.flat_map(volume.book_ids, fn id ->
      entry = volume.books[id]

      Stream.flat_map(entry.module.chapters(), fn {chapter, texts} ->
        texts
        |> Enum.with_index(1)
        |> Enum.map(fn {text, number} -> build_verse(volume, entry, chapter, number, text) end)
      end)
    end)
  end

  @doc false
  def random_verse(volume) do
    index = :rand.uniform(volume.verse_count) - 1
    volume |> stream() |> Stream.drop(index) |> Enum.at(0)
  end

  @reference ~r/^\s*(.+?)\s+(\d+)(?:\s*:\s*([\d\s,\-–—]+))?\s*$/u

  @doc false
  def parse_reference(volume, reference) when is_binary(reference) do
    case Regex.run(@reference, reference) do
      [_, name, chapter | rest] ->
        with {:ok, id} <- resolve(volume, name),
             {:ok, verses} <- parse_verses(rest) do
          {:ok, %{book: id, chapter: String.to_integer(chapter), verses: verses}}
        end

      nil ->
        {:error, :invalid_reference}
    end
  end

  @doc false
  def lookup(volume, reference) do
    with {:ok, %{book: id, chapter: chapter, verses: numbers}} <-
           parse_reference(volume, reference),
         entry = volume.books[id],
         {:ok, {^chapter, texts}} <- fetch_chapter(entry, chapter) do
      numbers = if numbers == :all, do: Enum.to_list(1..length(texts)//1), else: numbers

      numbers
      |> Enum.reduce_while({:ok, []}, fn number, {:ok, acc} ->
        case fetch_verse(texts, number) do
          {:ok, text} ->
            {:cont, {:ok, [build_verse(volume, entry, chapter, number, text) | acc]}}

          error ->
            {:halt, error}
        end
      end)
      |> case do
        {:ok, verses} -> {:ok, Enum.reverse(verses)}
        error -> error
      end
    end
  end

  @doc false
  def search(volume, query, opts) do
    matcher =
      case query do
        %Regex{} = regex ->
          &Regex.match?(regex, &1)

        query when is_binary(query) ->
          needle = String.downcase(query)
          &String.contains?(String.downcase(&1), needle)
      end

    verses =
      case Keyword.get(opts, :book) do
        nil ->
          stream(volume)

        ref ->
          {:ok, chapters} = volume |> book(ref) |> bang(ref) |> then(&chapters(volume, &1))
          Stream.flat_map(chapters, & &1.verses)
      end

    verses = Stream.filter(verses, &matcher.(&1.text))

    case Keyword.get(opts, :limit) do
      nil -> Enum.to_list(verses)
      limit -> Enum.take(verses, limit)
    end
  end

  @doc false
  def bang({:ok, value}, _ref), do: value

  def bang({:error, reason}, ref) do
    message = reason |> Atom.to_string() |> String.replace("_", " ")
    raise ArgumentError, "#{message}: #{inspect(ref)}"
  end

  ## Helpers

  defp resolve(volume, %Book{id: id}), do: resolve(volume, id)

  defp resolve(volume, id) when is_atom(id) do
    if Map.has_key?(volume.books, id), do: {:ok, id}, else: {:error, :book_not_found}
  end

  defp resolve(volume, name) when is_binary(name) do
    case Map.fetch(volume.name_index, normalize(name)) do
      {:ok, id} -> {:ok, id}
      :error -> {:error, :book_not_found}
    end
  end

  defp fetch_chapter(entry, number) do
    case List.keyfind(entry.module.chapters(), number, 0) do
      nil -> {:error, :chapter_not_found}
      chapter -> {:ok, chapter}
    end
  end

  defp fetch_verse(texts, number) when number >= 1 do
    case Enum.at(texts, number - 1) do
      nil -> {:error, :verse_not_found}
      text -> {:ok, text}
    end
  end

  defp fetch_verse(_texts, _number), do: {:error, :verse_not_found}

  defp parse_verses([]), do: {:ok, :all}

  defp parse_verses([spec]) do
    spec
    |> String.split(",", trim: true)
    |> Enum.reduce_while({:ok, []}, fn part, {:ok, acc} ->
      case part |> String.split(~r/[\-–—]/u) |> Enum.map(&Integer.parse(String.trim(&1))) do
        [{v, ""}] -> {:cont, {:ok, acc ++ [v]}}
        [{from, ""}, {to, ""}] when from <= to -> {:cont, {:ok, acc ++ Enum.to_list(from..to)}}
        _ -> {:halt, {:error, :invalid_reference}}
      end
    end)
  end

  defp build_chapter(volume, entry, {number, texts}) do
    %Chapter{
      volume: volume.id,
      book: entry.book.id,
      book_name: entry.book.name,
      number: number,
      reference: "#{entry.book.name} #{number}",
      url: "#{@site}/#{volume.url_path}/#{entry.url_slug}/#{number}?lang=eng",
      verses:
        texts
        |> Enum.with_index(1)
        |> Enum.map(fn {text, verse} -> build_verse(volume, entry, number, verse, text) end)
    }
  end

  defp build_verse(volume, entry, chapter, number, text) do
    %Verse{
      volume: volume.id,
      book: entry.book.id,
      book_name: entry.book.name,
      chapter: chapter,
      number: number,
      text: text,
      reference: "#{entry.book.name} #{chapter}:#{number}",
      url:
        "#{@site}/#{volume.url_path}/#{entry.url_slug}/#{chapter}?lang=eng&id=p#{number}#p#{number}"
    }
  end
end
