# This file is generated by scripts/generate_volume.py. Do not edit by hand.
defmodule ExChurchOfJesusChrist.Scriptures.DoctrineAndCovenants.Data.FrontMatter do
  @moduledoc false

  def all do
    %{
      title_page: [
        "The Doctrine and Covenants",
        "of The Church of Jesus Christ of Latter-day Saints",
        "Containing Revelations Given to Joseph Smith, the Prophet with Some Additions by His Successors in the Presidency of the Church"
      ]
    }
  end
end
