# This file is generated by scripts/generate_volume.py. Do not edit by hand.
defmodule ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data do
  @moduledoc false

  def books do
    [
    ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.FirstNephi,
    ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.SecondNephi,
    ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.Jacob,
    ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.Enos,
    ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.Jarom,
    ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.Omni,
    ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.WordsOfMormon,
    ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.Mosiah,
    ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.Alma,
    ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.Helaman,
    ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.ThirdNephi,
    ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.FourthNephi,
    ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.Mormon,
    ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.Ether,
    ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.Moroni
    ]
  end
end
