"""Generates the Book of Mormon data modules from the parsed JSON.

    curl -sL -o bom.txt https://www.gutenberg.org/cache/epub/17/pg17.txt
    python scripts/parse_book_of_mormon.py      # writes bom.json
    python scripts/generate_book_of_mormon.py   # writes lib/.../book_of_mormon/data/*.ex
"""
import json, os, sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "bom.json"
OUT = "lib/ex_church_of_jesus_christ/scriptures/book_of_mormon/data"

META = {
 "first_nephi":     ("FirstNephi", "1 Ne.", "1-ne", "The First Book of Nephi", "His Reign and Ministry", ["1 nephi", "1 ne", "1ne", "1nephi", "first nephi", "i nephi"]),
 "second_nephi":    ("SecondNephi", "2 Ne.", "2-ne", "The Second Book of Nephi", None, ["2 nephi", "2 ne", "2ne", "2nephi", "second nephi", "ii nephi"]),
 "jacob":           ("Jacob", "Jacob", "jacob", "The Book of Jacob", "The Brother of Nephi", ["jacob", "jac"]),
 "enos":            ("Enos", "Enos", "enos", "The Book of Enos", None, ["enos"]),
 "jarom":           ("Jarom", "Jarom", "jarom", "The Book of Jarom", None, ["jarom", "jar"]),
 "omni":            ("Omni", "Omni", "omni", "The Book of Omni", None, ["omni"]),
 "words_of_mormon": ("WordsOfMormon", "W of M", "w-of-m", "The Words of Mormon", None, ["words of mormon", "w of m", "wofm", "wom"]),
 "mosiah":          ("Mosiah", "Mosiah", "mosiah", "The Book of Mosiah", None, ["mosiah", "mos"]),
 "alma":            ("Alma", "Alma", "alma", "The Book of Alma", "The Son of Alma", ["alma"]),
 "helaman":         ("Helaman", "Hel.", "hel", "The Book of Helaman", None, ["helaman", "hel"]),
 "third_nephi":     ("ThirdNephi", "3 Ne.", "3-ne", "Third Nephi", "The Book of Nephi, the Son of Nephi, Who Was the Son of Helaman", ["3 nephi", "3 ne", "3ne", "3nephi", "third nephi", "iii nephi"]),
 "fourth_nephi":    ("FourthNephi", "4 Ne.", "4-ne", "Fourth Nephi", "The Book of Nephi, Who Is the Son of Nephi\u2014One of the Disciples of Jesus Christ", ["4 nephi", "4 ne", "4ne", "4nephi", "fourth nephi", "iv nephi"]),
 "mormon":          ("Mormon", "Morm.", "morm", "The Book of Mormon", None, ["mormon", "morm"]),
 "ether":           ("Ether", "Ether", "ether", "The Book of Ether", None, ["ether", "eth"]),
 "moroni":          ("Moroni", "Moro.", "moro", "The Book of Moroni", None, ["moroni", "moro", "mni"]),
}

def ex(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("#{", "\#{") + '"'

def ex_list(items, indent):
    if not items:
        return "[]"
    pad = " " * indent
    return "[\n" + ",\n".join(pad + "  " + ex(i) for i in items) + "\n" + pad + "]"

data = json.load(open(SRC, encoding="utf-8"))
os.makedirs(OUT, exist_ok=True)

for order, book in enumerate(data["books"], start=1):
    mod, abbr, url, title, subtitle, aliases = META[book["slug"]]
    chapters = []
    for c in book["chapters"]:
        chapters.append("    {%d,\n     %s}" % (c["number"], ex_list([v["text"] for v in c["verses"]], 5)))
    chapters_src = ",\n".join(chapters)
    subtitle_src = ex(subtitle) if subtitle else "nil"
    src = f'''# This file is generated by scripts/generate_book_of_mormon.py. Do not edit by hand.
defmodule ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.{mod} do
  @moduledoc false

  def metadata do
    %{{
      id: :{book["slug"]},
      order: {order},
      name: {ex(book["name"])},
      abbreviation: {ex(abbr)},
      url_slug: {ex(url)},
      title: {ex(title)},
      subtitle: {subtitle_src},
      introduction: {ex_list(book["introduction"], 6)},
      aliases: {ex_list(aliases, 6)}
    }}
  end

  @chapters [
{chapters_src}
  ]

  def chapters, do: @chapters
end
'''
    with open(os.path.join(OUT, book["slug"] + ".ex"), "w", encoding="utf-8", newline="\n") as f:
        f.write(src)

fm = data["front_matter"]
src = f'''# This file is generated by scripts/generate_book_of_mormon.py. Do not edit by hand.
defmodule ExChurchOfJesusChrist.Scriptures.BookOfMormon.Data.FrontMatter do
  @moduledoc false

  def title_page, do: {ex_list(fm["title_page"], 2)}

  def three_witnesses, do: {ex_list(fm["three_witnesses"], 2)}

  def eight_witnesses, do: {ex_list(fm["eight_witnesses"], 2)}
end
'''
with open(os.path.join(OUT, "front_matter.ex"), "w", encoding="utf-8", newline="\n") as f:
    f.write(src)
print("wrote", len(data["books"]) + 1, "files to", OUT)
