"""Generates the Elixir data modules for one volume of scripture from JSON.

    python scripts/generate_volume.py <volume.json>

The JSON document has this shape (all strings UTF-8, verse text without
verse numbers):

    {
      "volume": {"id": "book_of_mormon", "module": "BookOfMormon"},
      "front_matter": {"title_page": ["paragraph", ...], ...},      # optional
      "books": [
        {
          "id": "first_nephi",            # snake_case atom, unique across ALL volumes
          "module": "FirstNephi",         # module name under <Volume>.Data
          "name": "1 Nephi",              # canonical name used in references
          "abbreviation": "1 Ne.",        # abbreviation used on churchofjesuschrist.org
          "url_slug": "1-ne",             # path segment on churchofjesuschrist.org
          "title": "The First Book of Nephi",
          "subtitle": "His Reign and Ministry",   # or null
          "introduction": ["paragraph", ...],     # text before chapter 1, may be []
          "aliases": ["1 nephi", "1 ne", ...],    # extra names accepted in references
          "chapters": [{"number": 1, "verses": ["verse 1 text", "verse 2 text", ...]}]
        }
      ]
    }

Files are written to lib/ex_church_of_jesus_christ/scriptures/<volume id>/data/.
"""
import json, os, shutil, sys


def ex(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("#{", "\#{") + '"'


def ex_list(items, indent):
    if not items:
        return "[]"
    pad = " " * indent
    return "[\n" + ",\n".join(pad + "  " + ex(i) for i in items) + "\n" + pad + "]"


HEADER = "# This file is generated by scripts/generate_volume.py. Do not edit by hand.\n"


def main(path):
    data = json.load(open(path, encoding="utf-8"))
    volume = data["volume"]
    namespace = "ExChurchOfJesusChrist.Scriptures." + volume["module"] + ".Data"
    out = os.path.join("lib", "ex_church_of_jesus_christ", "scriptures", volume["id"], "data")
    shutil.rmtree(out, ignore_errors=True)
    os.makedirs(out)

    for order, book in enumerate(data["books"], start=1):
        chapters_src = ",\n".join(
            "    {%d,\n     %s}" % (c["number"], ex_list(c["verses"], 5)) for c in book["chapters"]
        )
        subtitle_src = ex(book["subtitle"]) if book.get("subtitle") else "nil"
        src = f'''{HEADER}defmodule {namespace}.{book["module"]} do
  @moduledoc false

  def metadata do
    %{{
      id: :{book["id"]},
      order: {order},
      name: {ex(book["name"])},
      abbreviation: {ex(book["abbreviation"])},
      url_slug: {ex(book["url_slug"])},
      title: {ex(book["title"])},
      subtitle: {subtitle_src},
      introduction: {ex_list(book.get("introduction", []), 6)},
      aliases: {ex_list(book.get("aliases", []), 6)}
    }}
  end

  @chapters [
{chapters_src}
  ]

  def chapters, do: @chapters
end
'''
        write(os.path.join(out, book["id"] + ".ex"), src)

    front = data.get("front_matter") or {}
    entries = ",\n".join(f"      {key}: {ex_list(paras, 6)}" for key, paras in front.items())
    src = f'''{HEADER}defmodule {namespace}.FrontMatter do
  @moduledoc false

  def all do
    %{{
{entries}
    }}
  end
end
'''
    write(os.path.join(out, "front_matter.ex"), src)

    modules = ",\n".join(f"    {namespace}.{b['module']}" for b in data["books"])
    src = f'''{HEADER}defmodule {namespace} do
  @moduledoc false

  def books do
    [
{modules}
    ]
  end
end
'''
    write(os.path.join(os.path.dirname(out), "data.ex"), src)
    verses = sum(len(c["verses"]) for b in data["books"] for c in b["chapters"])
    print(f"wrote {len(data['books'])} books, {verses} verses to {out}")


def write(path, src):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(src)


if __name__ == "__main__":
    main(sys.argv[1])
