# This file is generated by scripts/generate_volume.py. Do not edit by hand.
defmodule ExChurchOfJesusChrist.Scriptures.OldTestament.Data do
  @moduledoc false

  def books do
    [
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Genesis,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Exodus,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Leviticus,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Numbers,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Deuteronomy,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Joshua,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Judges,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Ruth,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.FirstSamuel,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.SecondSamuel,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.FirstKings,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.SecondKings,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.FirstChronicles,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.SecondChronicles,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Ezra,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Nehemiah,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Esther,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Job,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Psalms,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Proverbs,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Ecclesiastes,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.SongOfSolomon,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Isaiah,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Jeremiah,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Lamentations,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Ezekiel,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Daniel,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Hosea,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Joel,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Amos,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Obadiah,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Jonah,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Micah,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Nahum,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Habakkuk,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Zephaniah,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Haggai,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Zechariah,
    ExChurchOfJesusChrist.Scriptures.OldTestament.Data.Malachi
    ]
  end
end
